name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------
      # Build Next.js App Image
      # -----------------------
      - name: Build next-app image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -t ${{ secrets.IMAGE_NAME }}:latest .

      - name: Push next-app image
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:latest

      # -----------------------
      # Build Autoscaler Image
      # -----------------------
      - name: Build autoscaler image
        run: |
          docker build \
            -f autoscaler.Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/my-autoscaler:latest .

      - name: Push autoscaler image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-autoscaler:latest
